name: Update status.json

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch # Make sure this is in your package.json

      - name: Run updateStatus.js
        env:
          UPTIME_ROBOT_API_KEY: u2692690-656fe82844ad7140e68896c1
        run: node updateStatus.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add docs/status.json # Or just status.json if it's in the root
          git commit -m "Auto-update status.json" || echo "No changes"
          git push origin ${{ github.ref_name }}
